### ISSUE TITLE
command handler for `/creativesave` is only registered on first load-in

### ISSUE THREAD

**Issue by jrloken** [Allen-Wrench/CreativeWorldSave#2]
I believe e6584d666034e2f46ef3903d9855c78b8ccde01c introduced a regression which causes the command handler to only be loaded on the first "load in" of the game.  In practice, this means that when loading into a nexus server, the command is added on load in to the lobby, but then not for the subsequent load-in to the character's location on another server in the cluster, so running `/creativesave something` once you land on the destination server just sends it to chat.  It doesn't show up in `/help` either.

I tried removing  `MySession.OnLoading -= OnLoading;` from
```cs
		public void OnLoading() 
		{
			MySession.Static.OnReady += AddCommand;
			MySession.OnLoading -= OnLoading;
		}
```
 in Plugin.cs to make sure `AddCommand` is called on each load-in, and it fixes the command not working after the 2nd load-in, but I don't know if it re-introduces the crash from #1 yet.  The nexus server I play on is experiencing technical difficulties at the moment 😬

**Comment by Allen-Wrench** [comment]
Should be fixed with the new update. Check readme for new usage instructions.
